name: Build and Deploy

on:
  push:
    branches: master
  repository_dispatch:
    types: [contentful.deploy]

jobs:
  build-and-deploy:
    name: Build and deploy Portfolio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      
      - name: Install Project Dependencies
        run: npm install
        
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli  
                  
      - name: Build
        run: gatsby build
        env:
           CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
           CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}   
      
      - name: Deploy to S3 Bucket  
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: 'eu-central-1'   
           SOURCE_DIR: 'public'      
