name: Build and Deploy

on:
  push:
    branches: master
  repository_dispatch:
    types: [contentful.deploy]

jobs:
  build-and-deploy:
    name: Build and deploy Portfolio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      
      - name: Install Project Dependencies
        run: npm install
        
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli  
      
      - name: Install Gatsby Source
        run: npm install gatsby-source-contentful
                  
      - name: Build
        run: gatsby build
        env:
           CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
           CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}   
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: eu-central-1 

      - name: Upload files to S3
        run: |
           aws s3 sync public s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read --delete
           aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"   
