name: Test build

on:
  push:
    branches: [ deploy ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:        
    - uses: actions/checkout@v2
    - name: Setup Contentful
      run: npm install && npm run build
